spring:
  application:
    name: deviceApi
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:device-user}
    password: ${DB_PASS:device-password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.boot.web: DEBUG

server:
  port: 8081
